import 'package:flutter/material.dart';

// Colors
const Color kbackgroundColor = Color.fromARGB(68, 148, 176, 192);
const Color kDrawerSymbolColor = Colors.white70;
const Color kCardBackgoundColor = Color(0xFFe0eef6);
const Color kColorTieranzahlContainer = Color(0xFFe2b3ea);
const Color kColorKaelberanzahlContainer = Color(0xFFeac7b3);
const Color kColorAlarmContainer = Color(0xFFaf5b6a);
const Color kTopViewContainerBorderColor = Colors.black12;
const Color kAppBarBackgroundColor = Colors.blue;
const int kOpacity = 70;
const Color kwarningColor = Color.fromARGB(255, 128, 13, 5);
const Color kCardTitleTextColor = Color(0xFF2a0d5e);

const String description =
    "Der Grundstein für leistungsfähige, robuste Milchkühe und Mastrinder wird bereits bei der Haltung und beim Umgang mit dem tragenden Muttertier und in den ersten Lebensmomenten des Kalbes gelegt. Dennoch liegen die Kälberverluste, nicht nur in Deutschland, konstant auf einem inakzeptabel hohen Niveau. Daten-, Wissens- und Managementdefizite in der Haltung der Kälber und Jungtiere können eine mögliche Ursache dieser hohen Verlustraten sein. Auf der einen Seite sind neben den gesetzlichen Mindestanforderungen an die Jungtierhaltung darüberhinausgehende wissenschaftliche Erkenntnisse zur bestmöglichen Unterbringung und Versorgung sowie dem Gesundheitsmanagement für einen guten Start der neugeborenen Tiere ins Leben zugänglich. Auf der anderen Seite hat die kontinuierliche Erfassung und Bewertung der Tierdaten im Jungviehbereich bisher keinen Einzug in die landwirtschaftliche Praxis gehalten, obwohl gleichzeitig digitale Anwendungen und Tools für die Milchkuhherde zunehmend an Bedeutung gewinnen. Für den Jungviehbereich bestehen mangels ausreichender Daten bisher keine Möglichkeiten Defizite digital zu erkennen und durch Änderung im Management darauf zu reagieren. Daneben rücken Probleme der Kälberhaltung vermehrt in den Fokus gesellschaftlicher und politischer Anforderungen (Änderung der Tierschutz-Nutztierhaltungsverordnung sowie der Tierschutztransportverordnung, ANIT-Untersuchungsausschuss zu Tiertransporten, Initiative “End of the Cage Age”). Diese Herausforderungen der Kälberhaltung sind nur mit einer besseren Erfassung und Einspeisung bereits existierender bzw. leicht zu generierenden Daten und Beobachtungen in Praxisbetrieben zu bewältigen. Ziel des Vorhabens ist es mit einer auf daten-technischen Neuentwicklungen aufbauenden Erweiterung der bereits bestehenden und in der Praxis verbreiteten Apps der Landeskontrollverbände Nordrhein-Westfalen und Baden-Württemberg FokusMobil bzw. LKV-Rind-App neue Ansätze zur Dokumentation und zur Überwachung der Gesundheit bei Kälbern und Jungrindern praxisrelevant zu erforschen und zu entwickeln. Damit wären auch die korrelierenden weiteren biologischen Leistungen als spätere Milchkuh bzw. Masttier nutzbar und könnten das Bewusstsein der Milchviehhaltenden langfristig für ihre Jungtiere stärken. Anhand der gezielten Zusammenführung von manuell, automatisch und halbautomatisch erfassten Daten bei den Kälbern sowie historischen Daten bezüglich Milchleistung, Zucht und Tiergesundheit sollen neuartige Analyseansätze und Benchmarkingparameter im InnoKalb-Tool zur Entscheidungsunterstützung im Kälbermanagement beitragen. Eine verbesserte Kommunikation zwischen den jeweiligen tierhaltenden Betrieben im Sinne des Tierwohls und der Tiergesundheit sowie zur Schaffung von Ansätzen für Kooperationsmodelle ist ebenfalls Ziel des Projektes.";
